### ISSUE TITLE
Permission to sort-of-fork

### ISSUE THREAD

**Issue by jameswilddev** [svaarala/duktape-releases#1]
Hello!  I'd like to include just duktape.c, duktape.h and duk_config.h as a Git submodule in my project.  To do this however, I'd need to make a repository for this which effectively just mirrors the latest release from here, pre-unpacked.  Every time a new file is added to this repository I'd do a new commit with just its duktape.c/duktape.h/duk_config.h.  I'd call it duktape-latest, and explain in the project description that this is purely a mirror.

Is this something you'd be happy for me to do?

**Comment by svaarala** [comment]
Sure, sounds good. So this repo would provide pre-configured sources for the latest release, not master.

**Comment by jameswilddev** [comment]
Yeah.  Thanks for the great library!
